[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerContext = "backend"

[deploy]
startCommand = "node dist/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
